# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Q:/Mimas_Firmware/Patricks_LMK_code/Patricks_LMK_code.srcs/sources_1/ip/sys_clk_generator/sys_clk_generator.xci
# IP: The module: 'sys_clk_generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: q:/Mimas_Firmware/Patricks_LMK_code/Patricks_LMK_code.gen/sources_1/ip/sys_clk_generator/sys_clk_generator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clk_generator'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: q:/Mimas_Firmware/Patricks_LMK_code/Patricks_LMK_code.gen/sources_1/ip/sys_clk_generator/sys_clk_generator.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: q:/Mimas_Firmware/Patricks_LMK_code/Patricks_LMK_code.gen/sources_1/ip/sys_clk_generator/sys_clk_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: Q:/Mimas_Firmware/Patricks_LMK_code/Patricks_LMK_code.srcs/sources_1/ip/sys_clk_generator/sys_clk_generator.xci
# IP: The module: 'sys_clk_generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: q:/Mimas_Firmware/Patricks_LMK_code/Patricks_LMK_code.gen/sources_1/ip/sys_clk_generator/sys_clk_generator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: q:/Mimas_Firmware/Patricks_LMK_code/Patricks_LMK_code.gen/sources_1/ip/sys_clk_generator/sys_clk_generator.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: q:/Mimas_Firmware/Patricks_LMK_code/Patricks_LMK_code.gen/sources_1/ip/sys_clk_generator/sys_clk_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
