set_property SRC_FILE_INFO {cfile:Q:/Mimas_Firmware/Patricks_LMK_code/Patricks_LMK_code.srcs/constrs_1/imports/MiMas/Mimasa7Mini.xdc rfile:../../../Patricks_LMK_code.srcs/constrs_1/imports/MiMas/Mimasa7Mini.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN "N11"    IOSTANDARD LVCMOS33       SLEW FAST} [get_ports { clk }]     ;                # IO_L13P_T2_MRCC_14            Sch = CLK
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN "C16" } [get_ports {    LMKDATA     }]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN "B16" } [get_ports {    LMKLE       }]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN "A15" } [get_ports {    LMKCLK      }]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN "K15" } [get_ports {    LMKOE       }]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { IOSTANDARD LVCMOS25 PACKAGE_PIN "D10" } [get_ports {    CLK_SYNC    }]
